import type { Prisma } from '@prisma/client';
export declare const createExtractions: (dataArray: {
    operationId: string;
    processingJobId: string;
    documentId: string;
    documentType: string;
    confidence: number;
    originalFields: any;
    rawResponse?: any;
}[]) => Promise<Prisma.BatchPayload>;
export declare const findExtractionsByOperationId: (operationId: string) => Promise<{
    id: string;
    operationId: string;
    processingJobId: string;
    documentId: string;
    documentType: string;
    confidence: number;
    originalFields: Prisma.JsonValue;
    editedFields: Prisma.JsonValue | null;
    rawResponse: Prisma.JsonValue | null;
    status: import(".prisma/client").$Enums.ExtractionStatus;
    approvedBy: string | null;
    approvedAt: Date | null;
    reviewedAt: Date | null;
    reviewerNotes: string | null;
    version: number;
    lastExportedAt: Date | null;
    exportCount: number;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare const findExtractionById: (id: string) => Promise<{
    id: string;
    operationId: string;
    processingJobId: string;
    documentId: string;
    documentType: string;
    confidence: number;
    originalFields: Prisma.JsonValue;
    editedFields: Prisma.JsonValue | null;
    rawResponse: Prisma.JsonValue | null;
    status: import(".prisma/client").$Enums.ExtractionStatus;
    approvedBy: string | null;
    approvedAt: Date | null;
    reviewedAt: Date | null;
    reviewerNotes: string | null;
    version: number;
    lastExportedAt: Date | null;
    exportCount: number;
    createdAt: Date;
    updatedAt: Date;
} | null>;
export declare const updateExtractionById: (id: string, data: Prisma.ExtractionUpdateInput) => Promise<{
    id: string;
    operationId: string;
    processingJobId: string;
    documentId: string;
    documentType: string;
    confidence: number;
    originalFields: Prisma.JsonValue;
    editedFields: Prisma.JsonValue | null;
    rawResponse: Prisma.JsonValue | null;
    status: import(".prisma/client").$Enums.ExtractionStatus;
    approvedBy: string | null;
    approvedAt: Date | null;
    reviewedAt: Date | null;
    reviewerNotes: string | null;
    version: number;
    lastExportedAt: Date | null;
    exportCount: number;
    createdAt: Date;
    updatedAt: Date;
}>;
//# sourceMappingURL=extraction.repository.d.ts.map